name: 书源请求 (BookSource request)
description: 希望制作 xxx 小说网站的书源...
title: "书源请求：xxx 小说网（记得修改该示例标题，并移除该括号提示）"
labels: 书源请求
body:
  - type: markdown
    attributes:
      value: |
        > [!NOTE]
        > ***想要让我花费时间和精力免费帮你写书源，就请务必看完以下 `申请必读` ！***   
        > ***该项目仅仅是我业余自给自足顺便分享出来罢了，因此确保有充足的推荐理由，不要把我当工具人！***  

        另外，本项目只制作《阅读》3.X 版本的书源，不考虑也无法转换为 2.X 版本！
        ****
        发之前，请先搜下有没有类似的 [**Issues**](https://github.com/XIU2/Yuedu/issues) （包括[**关闭**](https://github.com/XIU2/Yuedu/issues?q=is%3Aissue+is%3Aclosed)的），请勿重复发起！   
        ****
        
        > [!IMPORTANT]
        > ### \# 申请必读：
        > 0. 请先去 [**源仓库**](https://www.yckceo.com/yuedu/shuyuan)、[**Yiove 综合书源库**](https://shuyuan.yiove.com/complex) 搜索一下，看有没有人写过该小说网站的书源了，避免重复造轮子
        > 1. 不接受 **`轻小说、R18 小说、听书、漫画、小说下载站(带在线阅读的除外)`** 等类型的网站申请（因为我不看这些类型）  
        > 2. 不接受 **`国内无法直连访问`** 的小说网站（被墙/主动屏蔽国内的，写出来如果没多少人能用也没意义了，除非真的质量很好）
        > 3. 不接受 **`内容质量差`** 的小说网站（正文中插入域名、广告等乱七八糟无关内容的，或存在被防盗的反义词、假章、错章等）  
        > 4. 如果只是因为某几本书在该网站更新快/无错误，那么请确保本项目的 **`所 有 书 源 都 无 法 满 足`**，否则我懒得费时间去制作~

        > **注意**：我写的书源都是**分享给大家使用**的，而非专门给你一个人写的，因此才会有以上要求。请确保你推荐的书源网站都满足，否则申请可能会被直接拒绝，望悉知。
        ****
  - type: textarea
    id: url
    attributes:
      label: 网站地址
      placeholder: https://...
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: 推荐原因
      description: 必填，不要写的太简略、敷衍，举几个例子（比如某本书什么的），否则我可能懒得费时间去检查网站内容质量！
      placeholder: 请输入理由并举个例子...
    validations:
      required: true